#!/usr/bin/env php
<?php

require_once $_SERVER['DOCUMENT_ROOT'] . 'vendor/autoload.php';

try {
    $command = \Skaleplan\Console\CommandFabric::getCommand($argv);
    $command->run();
} catch (\Skaleplan\Console\Exceptions\AbstractException $e) {
    echo $e->getMessage();
}
